name: Deploy to Aliyun
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."
          target: "/www/wwwroot/teacherlab.cn"
          rm: true
          strip_components: 0
          exclude: |
            .git
            .github
            .cursor
            习题转ppt
            背诵管理
            错题统计
            teacherelab
            *.md
            !教师实验室介绍稿.md
            *.cursorrule
            *.conf
            *.sh

