name: Deploy to Aliyun
on:
  push:
    branches: [ main ] # 确认你的主分支是 main 还是 master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.ALIYUN_IP }}
          REMOTE_USER: ${{ secrets.ALIYUN_USER }}
          # 下面这行填宝塔里生成的根目录！
          TARGET: "/www/wwwroot/teacherlab.top"
          EXCLUDE: "/.git/, /.github/"